#!/usr/bin/env python3
"""Build the compact, auditable Safety Swarm dataset used by the showcase."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REPORT = (
    ROOT
    / "docs"
    / "evidence"
    / "safety-swarm-v2-formal-2026-07-30"
    / "formal-report.json"
)
OUTPUT = ROOT / "showcase" / "app" / "safetySwarmFormal.generated.ts"

STOP_REASON_CODES = {
    "safe": "S",
    "clutter_contact": "C",
    "stability_below_minimum": "M",
    "clearance_below_minimum": "G",
    "unreachable": "U",
    "task_failure": "T",
}


def compact_label(candidate_id: str) -> str:
    if candidate_id.startswith("yaw_+00.0_offset"):
        return "0° · direct"

    parts = candidate_id.split("_")
    yaw_value = float(parts[1])
    yaw = "0" if yaw_value == 0 else f"{yaw_value:+g}"
    retreat = float(parts[3])
    return f"{yaw}° · R{int(round(retreat * 1000))}"


def main() -> None:
    report = json.loads(REPORT.read_text())
    results = sorted(
        report["results"],
        key=lambda item: (item["candidate_index"], item["env_index"]),
    )
    summaries = {
        summary["candidate_index"]: summary
        for summary in report["candidate_summaries"]
    }

    rows = []
    for candidate_index in range(report["summary"]["candidate_count"]):
        candidate_results = [
            item for item in results if item["candidate_index"] == candidate_index
        ]
        summary = summaries[candidate_index]
        outcomes = "".join(
            STOP_REASON_CODES[item["primary_stop_reason"]]
            for item in candidate_results
        )
        if len(outcomes) != report["summary"]["world_count_per_candidate"]:
            raise ValueError(
                f"candidate {candidate_index} has {len(outcomes)} outcomes"
            )
        rows.append(
            {
                "candidateIndex": candidate_index,
                "candidateId": summary["candidate_id"],
                "label": compact_label(summary["candidate_id"]),
                "qualifies": summary["qualifies"],
                "selected": (
                    summary["candidate_id"]
                    == report["summary"]["selected_candidate_id"]
                ),
                "safeWorldCount": summary["safe_world_count"],
                "contactWorldCount": summary["contact_world_count"],
                "worstCaseClearanceMm": round(
                    summary["worst_case_clearance_m"] * 1000, 6
                ),
                "fifthPercentileClearanceMm": round(
                    summary["fifth_percentile_clearance_m"] * 1000, 6
                ),
                "minimumStability": round(summary["minimum_stability"], 6),
                "outcomes": outcomes,
            }
        )

    payload = {
        "reportSha256": report["report_sha256"],
        "decision": report["summary"]["decision"],
        "selectedCandidateId": report["summary"]["selected_candidate_id"],
        "candidateCount": report["summary"]["candidate_count"],
        "worldCountPerCandidate": report["summary"]["world_count_per_candidate"],
        "candidateWorldCount": report["summary"]["candidate_world_count"],
        "safeCandidateWorldCount": report["summary"]["safe_candidate_world_count"],
        "contactCandidateWorldCount": report["summary"][
            "contact_candidate_world_count"
        ],
        "qualifyingCandidateCount": len(
            report["summary"]["qualifying_candidate_ids"]
        ),
        "batchedExecutionWallSeconds": round(
            report["summary"]["batched_execution_wall_seconds"], 6
        ),
        "totalEnvironmentSteps": report["summary"]["total_environment_steps"],
        "environmentStepsPerSecond": round(
            report["summary"]["environment_steps_per_second"], 6
        ),
        "candidateWorldsPerSecond": round(
            report["summary"]["candidate_worlds_per_second"], 6
        ),
        "meanGpuUtilizationPct": round(
            report["gpu_telemetry"]["mean_gpu_utilization_pct"], 6
        ),
        "maxGpuUtilizationPct": report["gpu_telemetry"][
            "max_gpu_utilization_pct"
        ],
        "maxVramUsedBytes": int(report["gpu_telemetry"]["max_vram_used_bytes"]),
        "deviceName": report["device"]["name"],
        "hipVersion": report["device"]["hip_version"],
        "torchVersion": report["device"]["torch_version"],
        "genesisVersion": report["device"]["genesis_version"],
    }

    output = (
        "// Generated by scripts/build_showcase_safety_swarm_data.py.\n"
        "// Source: docs/evidence/safety-swarm-v2-formal-2026-07-30/formal-report.json\n"
        "// Do not edit by hand.\n\n"
        f"export const safetySwarmFormal = {json.dumps(payload, indent=2)} as const;\n\n"
        f"export const safetySwarmRows = {json.dumps(rows, indent=2)} as const;\n"
    )
    OUTPUT.write_text(output)
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
